"""crear tabla links

Revision ID: 278ef5198bc9
Revises:
Create Date: 2026-08-27 20:33:04.991279

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278ef5198bc9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Generada con autogenerate y AJUSTADA A MANO: autogenerate escribio
    # (CURRENT_TIMESTAMP) con parentesis, que es sintaxis de SQLite -- el motor
    # de desarrollo. Sin parentesis es SQL estandar y vale en SQLite y en
    # Postgres. Leccion: las migraciones autogeneradas SIEMPRE se revisan.
    op.create_table(
        "links",
        sa.Column("slug", sa.String(length=16), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###
